version: '3.8'

services:
  backend:
    build:
      context: ../backend/app
    ports:
      - "8000:8000"
    env_file:
      - ../.env
  frontend:
    build:
      context: ../frontend
    ports:
      - "8501:8501"
    env_file:
      - ../.env
